### PR TITLE
Bulk loader allocates reserved predicates in first reduce shard.

### LINKED ISSUE #3968: Can’t Query Type Data Inserted by Bulk Loader
### What version of Dgraph are you using?

Dgraph version   : v1.1.0
Dgraph SHA-256   : 7d4294a80f74692695467e2cf17f74648c18087ed7057d798f40e1d3a31d2095
Commit SHA-1     : ef7cdb28
Commit timestamp : 2019-09-04 00:12:51 -0700
Branch           : HEAD
Go version       : go1.12.7

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, OS)?

Attempted on Ubuntu 18.04 and using Dgraph docker

### Steps to reproduce the issue (command/config used to run Dgraph).

Start Zero (the commands are actually in the docker-compose file)

```
dgraph zero --my=zero:5080
```

Feed data and schema into Dgraph bulk

data file
```
_:brand1 <dgraph.type> "Brand" .
_:brand1 <name> "brand1" .
_:brand2 <dgraph.type> "Brand" .
_:brand2 <name> "brand2" .

_:product1 <dgraph.type> "Product" .
_:product1 <brand> _:brand1 .
_:product1 <name> "name1" .
_:product1 <pid> "abc" .

_:product2 <dgraph.type> "Product" .
_:product2 <brand> _:brand2 .
_:product2 <name> "name2" .
_:product2 <pid> "123" .

_:product3 <dgraph.type> "Product" .
_:product3 <brand> _:brand2 .
_:product3 <name> "name3" .
_:product3 <pid> "ab1" .
```
schema file
```
type Product {
  name: string
  brand: uid
  pid: string
}

type Brand {
  name: string
}

name: string @index(term)  .
pid: string @index(hash)  .
brand: uid .
```

Run Dgraph Bulk on data and schema
```
dgraph bulk --schema ./data/smallschema.txt -f ./data/small.txt  --format=rdf --reduce_shards=2 --num_go_routines=2 --map_shards=2
```

Start alphas pointing to the generated directories

```
dgraph alpha --my=server:7080 --lru_mb=2048 --zero=zero:5080 -p out/0/p/
dgraph alpha --my=server:7081 --lru_mb=2048 --zero=zero:5080 -p out/1/p/ -o=1
```

### Expected behaviour and actual result.

Query all objects with type Product
```
  q(func: type(Product)) {
    name
    uid
  }
```

Expected all product objects returned
Actual result is an empty result

Discussion link on forums: https://discuss.dgraph.io/t/cant-query-type-data-on-bulk-loader/5038

### PR DESCRIPTION
**Pull request by martinmr**
This PR contains a couple of related changes.

- Bulk loader forces reserved predicates to end up in the first reduce shard. It
  also writes a file in the posting directories with the proposed group ID for
  each shard.
- Dgraph looks at that file during startup and uses it to request the right group
  ID from zero.

The change is being tested by modifying the 21million test to use multiple groups
and add a new query to verify the number of nodes with a `dgraph.type` predicate.
If the test runs without the fix, dgraph.type sometime ends up in a different group. 

Fixes #3968.

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/4202)

### CODE REVIEW

File: dgraph/cmd/bulk/run.go [hunk 1]
```diff
@@ -192,6 +192,13 @@ func run() {
 		dir := filepath.Join(opt.OutDir, strconv.Itoa(i), "p")
 		x.Check(os.MkdirAll(dir, 0700))
 		opt.shardOutputDirs = append(opt.shardOutputDirs, dir)
+
+		groupFile := filepath.Join(dir, "group_id")
+		f, err := os.OpenFile(groupFile, os.O_CREATE|os.O_WRONLY, 0600)
+		x.Check(err)
+		x.Check2(f.WriteString(strconv.Itoa(i+1)))
```
Comment (golangcibot) [inline dgraph/cmd/bulk/run.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)
```suggestion
		x.Check2(f.WriteString(strconv.Itoa(i + 1)))
```

File: edgraph/server.go [hunk 2]
```diff
@@ -96,8 +99,19 @@ func InitServerState() {
...
 	go State.fillTimestampRequests()
+
+	contents, err := ioutil.ReadFile(filepath.Join(Config.PostingDir, groupFile))
+	if err != nil {
+		return
+	}
+
+	glog.Infof("Found group_id file inside posting directory %s. Will attempt to read.",
+		Config.PostingDir)
+	groupId, err := strconv.ParseUint(strings.TrimSpace(string(contents)), 0, 32)
```
Comment (golangcibot) [inline edgraph/server.go]: ineffectual assignment to `err` (from `ineffassign`)
