### PR TITLE
Fix StreamWriter usage in bulk loader

### LINKED ISSUE #3625: Bulk loader crashes after stream writer changes
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
Failed on 9138f23d73ae3c6cfba72ec6129eef13b110b438
Worked on 113649d53eab9220ba3541bd37150c1031297154

- Have you tried reproducing the issue with latest release?
Yes

- Steps to reproduce the issue (command/config used to run Dgraph).
Run `dgraph bulk  -f /tmp/small_posts --schema /home/animesh/dgraph/schema --format rdf`.
Data and schema can be found in comments.

- Error
```
I0703 18:32:13.554233   18586 init.go:93] 

Dgraph version   : v1.0.12-rc3-560-g9138f23d
Commit SHA-1     : 9138f23d
Commit timestamp : 2019-06-30 20:33:53 +0530
Branch           : HEAD
Go version       : go1.12.5

For Dgraph official documentation, visit https://docs.dgraph.io.
For discussions about Dgraph     , visit https://discuss.dgraph.io.
To say hi to the community       , visit https://dgraph.slack.com.

Licensed variously under the Apache Public License 2.0 and Dgraph Community License.
Copyright 2015-2018 Dgraph Labs, Inc.


{
	"DataFiles": "/tmp/small_posts",
	"DataFormat": "rdf",
	"SchemaFile": "/home/animesh/dgraph/schema",
	"OutDir": "./out",
	"ReplaceOutDir": false,
	"TmpDir": "tmp",
	"NumGoroutines": 16,
	"MapBufSize": 67108864,
	"SkipMapPhase": false,
	"CleanupTmp": true,
	"NumReducers": 1,
	"Version": false,
	"StoreXids": false,
	"ZeroAddr": "localhost:5080",
	"HttpAddr": "localhost:8080",
	"IgnoreErrors": false,
	"CustomTokenizers": "",
	"NewUids": false,
	"MapShards": 1,
	"ReduceShards": 1
}
Connecting to zero at localhost:5080
Processing file (1 out of 1): /tmp/small_posts
Shard tmp/shards/000 -> Reduce tmp/shards/shard_0/000
2019/07/03 18:32:14 Inter: Biggest(j-1) 
00000000  00 00 0d 43 68 6f 73 65  6e 2e 41 6e 73 77 65 72  |...Chosen.Answer|
00000010  00 00 00 00 00 00 02 81  7a c2 ff ff ff ff ff ff  |........z.......|
00000020  d8 e5                                             |..|

 vs Smallest(j): 
00000000  00 00 0a 48 61 73 2e 41  6e 73 77 65 72 08 00 00  |...Has.Answer...|
00000010  00 00 01 ff ff ff ff ff  ff d8 e5                 |...........|

: level=1 j=1 numTables=3
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelHandler).validate
	/home/animesh/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/util.go:55
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).validate
	/home/animesh/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/util.go:33
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*StreamWriter).Flush
	/home/animesh/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream_writer.go:184
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*reducer).run.func1
	/home/animesh/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/reduce.go:75
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
Levels Controller
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).validate
	/home/animesh/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/util.go:34
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*StreamWriter).Flush
	/home/animesh/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream_writer.go:184
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*reducer).run.func1
	/home/animesh/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/reduce.go:75
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337

github.com/dgraph-io/dgraph/x.Check
	/home/animesh/go/src/github.com/dgraph-io/dgraph/x/error.go:42
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*reducer).run.func1
	/home/animesh/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/reduce.go:76
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
```

### PR DESCRIPTION
**Pull request by manishrjain**
Last remaining KVs were not getting their StreamId set during reduce phase. This PR fixes that.

Fixes #3625 .

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/3635)

### CODE REVIEW

File: dgraph/cmd/bulk/reduce.go [hunk 1]
```diff
@@ -139,34 +139,42 @@ func (r *reducer) encodeAndWrite(
 	writer *badger.StreamWriter, entryCh chan []*pb.MapEntry, closer *y.Closer) {
 	defer closer.Done()
 
-	preds := make(map[string]uint32)
-
 	var listSize int
 	list := &bpb.KVList{}
+
+	preds := make(map[string]uint32)
+	setStreamId := func(kv *bpb.KV) {
```
Comment (golangcibot) [inline dgraph/cmd/bulk/reduce.go]: var `setStreamId` should be `setStreamID` (from `golint`)

File: dgraph/cmd/bulk/reduce.go [hunk 2]
```diff
@@ -139,34 +139,42 @@ func (r *reducer) encodeAndWrite(
...
+		pk := x.Parse(kv.Key)
+		x.AssertTrue(len(pk.Attr) > 0)
+
+		// We don't need to consider the data prefix, count prefix, etc. because each predicate has
+		// a list of sorted keys the way they are produced.
+		streamId := preds[pk.Attr]
```
Comment (golangcibot) [inline dgraph/cmd/bulk/reduce.go]: var `streamId` should be `streamID` (from `golint`)
