### PR TITLE
graphql: fix __typename bug + add __typename tests in fragments

### LINKED ISSUE #4925: GraphQL __typename response on mutations differs in some cases
### What version of Dgraph are you using?
v2.0.0-beta (Docker image)

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
RAM: 16GB
Linux 

### Steps to reproduce the issue (command/config used to run Dgraph).
I use the Altair GraphQL Client for the Requests

**Schema:**
```
type Stuff {
  id: ID!
  title: String!
  user: String!
}
```
**Mutation Request 1:**
```
mutation m {
  addStuff(input: [
    { title: "Hello World!", user: "birnsen"}
  ])
  {
    __typename
  }
}
```
**Response 1:**
```
{
  "data": {
    "addStuff": {
      "__typename": "AddStuffPayload"
    }
  }
}
```
**Mutation Request 2:**
```
mutation m {
  addStuff(input: [
    { title: "Hello World!", user: "birnsen"}
  ])
  {
    stuff {
      id
      __typename
    }
    __typename
  }
}
```
**Response 2:**
```
{
  "data": {
    "addStuff": {
      "stuff": [
        {
          "id": "0x3",
          "__typename": "Stuff"
        }
      ]
    }
  }
}
```

### Expected behaviour and actual result.
I expected that the second request returned with:
```
{
  "data": {
    "addStuff": {
      "stuff": [
        {
          "id": "0x3",
          "__typename": "Stuff"
        }
      ],
      "__typename": "AddStuffPayload"
    }
  }
}
```

Thread on discuss: https://discuss.dgraph.io/t/graphql-typename-response-on-mutations-differs-in-some-cases/6112

### PR DESCRIPTION
**Pull request by abhimanyusinghgaur**
Fixes #4925.

In addition, it also adds tests for  __typename in fragments, a small fix for supporting fragment without a type condition, and makes numUids work with alias.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/5002)

 
 

Docs Preview: [Dgraph Preview](https://dgraph-4b302e2b2e-55721.surge.sh)

### CODE REVIEW

File: graphql/resolve/resolver.go [hunk 1]
```diff
@@ -445,18 +478,82 @@ func removeObjectCompletion(cf CompletionFunc) CompletionFunc {
...
 //   `addFoo(...) { foo { ... } }`
 // What's resolved initially is
 //   `foo { ... }`
 // So `addFoo: ...` is added.
-func addRootFieldCompletion(name string, cf CompletionFunc) CompletionFunc {
-	return CompletionFunc(func(
-		ctx context.Context, field schema.Field, result []byte, err error) ([]byte, error) {
+func addRootFieldCompletion(name string, cf MutationCompletionFunc) MutationCompletionFunc {
+	return MutationCompletionFunc(func(
+		ctx context.Context, mutation schema.Mutation, numUids int, result []byte, err error) ([]byte, error) {
```
Comment (golangcibot) [inline graphql/resolve/resolver.go]: line is 105 characters (from `lll`)

File: graphql/resolve/resolver.go [hunk 2]
```diff
@@ -478,11 +575,11 @@ func addRootFieldCompletion(name string, cf CompletionFunc) CompletionFunc {
 // A mutation always looks like
 //   `addFoo(...) { foo { ... } }`
 // But cf's error paths begin at `foo`, so `addFoo` needs to be added to all.
-func addPathCompletion(name string, cf CompletionFunc) CompletionFunc {
-	return CompletionFunc(func(
-		ctx context.Context, field schema.Field, result []byte, err error) ([]byte, error) {
+func addPathCompletion(name string, cf MutationCompletionFunc) MutationCompletionFunc {
+	return MutationCompletionFunc(func(
+		ctx context.Context, mutation schema.Mutation, numUids int, result []byte, err error) ([]byte, error) {
```
Comment (golangcibot) [inline graphql/resolve/resolver.go]: line is 105 characters (from `lll`)

File: graphql/resolve/resolver.go [hunk 3]
```diff
@@ -445,18 +478,82 @@ func removeObjectCompletion(cf CompletionFunc) CompletionFunc {
...
+		queryField := mutation.QueryField()
+		res, err := cf(ctx, queryField, result, err)
+		selSet := mutation.SelectionSet()
+		n := len(selSet)
+
+		if len(res) == 0 && n == 1 && selSet[0].Name() == queryField.Name() {
+			return nil, err
+		}
+
+		addComma := true
```
Comment (golangcibot) [inline graphql/resolve/resolver.go]: ineffectual assignment to `addComma` (from `ineffassign`)

File: graphql/e2e/common/mutation.go [hunk 4]
```diff
@@ -2881,3 +2881,85 @@ func passwordTest(t *testing.T) {
...
+				__typename
+				numUids
+			}
+		}`,
+	}
+
+	gqlResponse = addStateParams.ExecuteAsPost(t, graphqlURL)
+	requireNoGQLErrors(t, gqlResponse)
+
+	addStateExpected = `{"addState":{"state":[{"xcode":"S2"}],"__typename":"AddStatePayload","numUids":1}}`
```
Comment (golangcibot) [inline graphql/e2e/common/mutation.go]: line is 104 characters (from `lll`)
