### PR TITLE
[BREAKING] Language sorting on Indexed data.

### LINKED ISSUE #4005: Values are not sorted properly
### What version of Dgraph are you using?
master
### Have you tried reproducing the issue with the latest release?
Yes

### Steps to reproduce the issue (command/config used to run Dgraph).
Just populate cluster with this data
̍https://github.com/dgraph-io/dgraph/blob/master/query/common_test.go#L269
and run the this query
```
{
		q(func:has(name), orderdesc: name, first:5) {
			 name
		 }
	 }
```

### Expected behaviour and actual result.
actual result 
```
{
  "data": {
    "q": [
      {
        "name": ""
      },
      {
        "name": ""
      },
      {
        "name": "Badger"
      },
      {
        "name": "name"
      },
      {
        "name": "expand"
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 14640,
      "processing_ns": 375499571,
      "encoding_ns": 28760,
      "assign_timestamp_ns": 503321
    },
    "txn": {
      "start_ts": 98
    }
  }
}
```
Expected everything to be sorted

### PR DESCRIPTION
**Pull request by arijitAD**
This will fix the sorting of an indexed field having lang directive.
Fixes #4005 
This PR change the data format for predicate that has lang directive and exact index.
Users upgrading from older version of dgraph must rebuild the index.
Example: 
name: string @index(exact) @lang .
Since name predicate has lang directive and exact index. This needs to be deleted and recreated again.
Alter the schema as
name: string @lang .
This will delete the old index data and the alter the schema as
name: string @index(exact) @lang .
This will recreate the index with new data format.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/4316)

### CODE REVIEW

File: tok/tok.go [hunk 1]
```diff
@@ -303,6 +307,34 @@ func (t ExactTokenizer) Identifier() byte { return IdentExact }
 func (t ExactTokenizer) IsSortable() bool { return true }
 func (t ExactTokenizer) IsLossy() bool    { return false }
 
+// LangTokenizer returns the exact string along with language prefix as a token.
+type LangTokenizer struct {
+	lang string
```
Comment (golangcibot) [inline tok/tok.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)
