### PR TITLE
Limit UIDs per variable in upsert

### LINKED ISSUE #4021: Upsert Block fails when processing multiple nodes
### What version of Dgraph are you using?
    Dgraph version   : v1.1.0  
    Dgraph SHA-256   :  7d4294a80f74692695467e2cf17f74648c18087ed7057d798f40e1d3a31d2095
    Commit SHA-1     : ef7cdb28
    Commit timestamp : 2019-09-04 00:12:51 -0700
    Branch           : HEAD
    Go version       : go1.12.7

### Have you tried reproducing the issue with the latest release?
    yes

### What is the hardware spec (RAM, OS)?
    Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz ，linux， 128G

### Steps to reproduce the issue (command/config used to run Dgraph).
I want to upgraph dgraph from 1.0.15 to 1.1.0。now dgraph 1.1.0 has support for a type system。 use the expand() function, the use of the type system is required。However, there is no dgraph.type in the data of dgraph1.0.15 export。The data exported has 30000000 nodes, 
I need to add dgraph.type to each node.

The command:

    curl -H "Content-Type: application/rdf" -X POST 10.134.27.30:8281/mutate?commitNow=true -d  $'
    upsert {
      query {
        v as var(func: has(xid))
      }

      mutation {
        set {
          uid(v) <dgraph.type> "Thing" .
        }
      }
    }
    ' | jq

### Expected behaviour and actual result.
I want to add dgraph.type to each node. But dgraph.ERROR shows:
image

### PR DESCRIPTION
**Pull request by mangalaman93**
fixes #4021

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/4268)

### CODE REVIEW

File: edgraph/server.go [hunk 1]
```diff
@@ -586,170 +494,129 @@ func (s *Server) doMutate(ctx context.Context, req *api.Request, authorize int)
...
+	if len(qc.req.Query) == 0 || len(qc.gmuList) == 0 {
+		return qc.req.Query
+	}
+
+	qc.condVars = make([]string, len(qc.req.Mutations))
+	upsertQuery := strings.TrimSuffix(qc.req.Query, "}")
+	for i, gmu := range qc.gmuList {
+		isCondUpsert := strings.TrimSpace(gmu.Cond) != ""
+		if isCondUpsert {
+			qc.condVars[i] = fmt.Sprintf("__dgraph_%d__", rand.Int())
```
Comment (golangcibot) [inline edgraph/server.go]: G404: Use of weak random number generator (math/rand instead of crypto/rand) (from `gosec`)
