### PR TITLE
contrib: Use xgo to use Cgo in cross-compiled release builds.

### LINKED ISSUE #4995: Crash on Darwin (zstd compression)
### What version of Dgraph are you using?
v20.03.0-beta.20200320

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
macOS Catalina, 32GB of RAM and 8GB from another machine (tested in both).

### Steps to reproduce the issue (command/config used to run Dgraph).

1 - Start Zero and Alpha
2- Start a Liveload with https://discuss.dgraph.io/t/dgraph-20-03-beta-importing-dump-from-1-2-2-fails/6165
```
./dgraph live -f /Users/micheldiz/Desktop/testplace/1million.rdf.gz  -s /Users/micheldiz/Desktop/testplace/1million.schema.txt
```

And it crashes.

### Expected behaviour and actual result.

Alpha log

```
I0321 12:42:21.575111    5344 server.go:1122] Got Alter request from "127.0.0.1:54357"
I0321 12:42:21.585760    5344 server.go:275] Got schema: &{Preds:[predicate:"director.film" value_type:UID directive:REVERSE count:true list:true  predicate:"actor.film" value_type:UID count:true list:true  predicate:"genre" value_type:UID directive:REVERSE count:true list:true  predicate:"initial_release_date" value_type:DATETIME directive:INDEX tokenizer:"year"  predicate:"rating" value_type:UID directive:REVERSE list:true  predicate:"country" value_type:UID directive:REVERSE list:true  predicate:"loc" value_type:GEO directive:INDEX tokenizer:"geo"  predicate:"name" value_type:STRING directive:INDEX tokenizer:"hash" tokenizer:"term" tokenizer:"trigram" tokenizer:"fulltext" lang:true  predicate:"starring" value_type:UID count:true list:true  predicate:"performance.character_note" value_type:STRING lang:true  predicate:"tagline" value_type:STRING lang:true  predicate:"cut.note" value_type:STRING lang:true  predicate:"rated" value_type:UID directive:REVERSE list:true  predicate:"email" value_type:STRING directive:INDEX tokenizer:"exact" upsert:true ] Types:[]}
I0321 12:42:21.590560    5344 groups.go:491] Serving tablet for: director.film
I0321 12:42:21.594929    5344 groups.go:491] Serving tablet for: actor.film
I0321 12:42:21.599148    5344 groups.go:491] Serving tablet for: genre
I0321 12:42:21.603570    5344 groups.go:491] Serving tablet for: initial_release_date
I0321 12:42:21.608083    5344 groups.go:491] Serving tablet for: rating
I0321 12:42:21.612698    5344 groups.go:491] Serving tablet for: country
I0321 12:42:21.626810    5344 groups.go:491] Serving tablet for: loc
I0321 12:42:21.632691    5344 groups.go:491] Serving tablet for: name
I0321 12:42:21.638071    5344 groups.go:491] Serving tablet for: starring
I0321 12:42:21.644099    5344 groups.go:491] Serving tablet for: performance.character_note
I0321 12:42:21.648729    5344 groups.go:491] Serving tablet for: tagline
I0321 12:42:21.652904    5344 groups.go:491] Serving tablet for: cut.note
I0321 12:42:21.657196    5344 groups.go:491] Serving tablet for: rated
I0321 12:42:21.670804    5344 groups.go:491] Serving tablet for: email
I0321 12:42:21.677699    5344 draft.go:136] Operation started with id: opIndexing
I0321 12:42:21.677748    5344 index.go:1054] Deleting reverse index for director.film
I0321 12:42:21.677760    5344 draft.go:104] Operation completed with id: opRollup
I0321 12:42:21.677764    5344 log.go:34] Writes flushed. Stopping compactions now...
2020/03/21 12:42:21 zstd compression requires building badger with cgo enabled

github.com/dgraph-io/badger/v2/y.Wrap
	/tmp/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200316175624-91c31ebe8c22/y/error.go:71
github.com/dgraph-io/badger/v2/y.Check
	/tmp/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200316175624-91c31ebe8c22/y/error.go:43
github.com/dgraph-io/badger/v2/table.(*Builder).handleBlock
	/tmp/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200316175624-91c31ebe8c22/table/builder.go:143
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373

```

### PR DESCRIPTION
**Pull request by danielmai**
### What does this PR do?

This updates the release.sh script to use xgo for Linux, Windows, and Darwin builds. 

### Motivation

This is to fix the panics related to Badger compression which only uses Zstd when Cgo is enabled. See #4995.

### Components affected by this PR 

Darwin and Windows release builds moving forward (v20.03.0 were already built with this change). Linux builds are working fine.

### Does this PR break backwards compatibility?  

No.

### Fixes 
Fixes #4995

### More 

This uses https://github.com/techknowlogick/xgo/, which is a maintained fork of https://github.com/karalabe/xgo.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/5120)

### CODE REVIEW

File: contrib/release.sh [hunk 1]
```diff
@@ -118,66 +120,57 @@ popd
 
 # Build Windows.
 pushd $basedir/dgraph/dgraph
-  env GOOS=windows GOARCH=amd64 go get -v -d .
-  env GOOS=windows GOARCH=amd64 GO111MODULE=on go build -v -o dgraph-windows-amd64.exe -ldflags \
+  xgo -image="$XGO_IMAGE" --targets=windows/amd64 -ldflags \
```
Comment (gja) [inline contrib/release.sh:123]: Is there any benefits to doing this in this way instead of actually compiling on Windows with a CI?

**Comment by danielmai** [comment]
I'll merge this since this fixes release build issues mentioned in #4995. We can decide to move away from xgo later if we start building alpine images.
