### PR TITLE
Gitlw/fix json facet

### LINKED ISSUE #2867: anyofterms does not work for facet created by JSON mutation
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
tried latest "latest" @ dockerhub and v1.0.12-rc1 

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
16gb, linux

- Steps to reproduce the issue (command/config used to run Dgraph).
Create any facet with a string value.

Query filter it with anyofterms

- Expected behaviour and actual result.

Expected: i can filter with anyofterms, so e.g. if the value of the facet is "READ" and i filter for anyofterms(permission, "READ WRITE"), i will get a result

Actual:
well, anyofterms does not work. the value is not returned. i can only use eq.
**BUT! This is only the case if i performed the mutation for this facet with the JSON API (from dgo). If i do it with the RDF syntax in ratel, it works!**

### PR DESCRIPTION
**Pull request by gitlw**
fixes #2867 
screenshot from 2019-01-09 10-57-02

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2885)

### CODE REVIEW

File: rdf/parse.go [hunk 1]
```diff
@@ -275,17 +275,17 @@ func isNewline(r rune) bool {
...
-	"xs:date":            types.DateTimeID,
-	"xs:dateTime":        types.DateTimeID,
-	"xs:int":             types.IntID,
-	"xs:positiveInteger": types.IntID,
-	"xs:boolean":         types.BoolID,
-	"xs:double":          types.FloatID,
-	"xs:float":           types.FloatID,
-	"xs:base64Binary":    types.BinaryID,
-	"geo:geojson":        types.GeoID,
+	"xs:password":                                      types.PasswordID,
```
Comment (golangcibot) [inline rdf/parse.go]: File is not `goimports`-ed (from `goimports`)

File: edgraph/nquads_from_json.go [hunk 2]
```diff
@@ -28,7 +28,7 @@ import (
 	"github.com/dgraph-io/dgraph/types"
 	"github.com/dgraph-io/dgraph/types/facets"
 	"github.com/dgraph-io/dgraph/x"
-	geom "github.com/twpayne/go-geom"
+	"github.com/twpayne/go-geom"
```
Comment (golangcibot) [inline edgraph/nquads_from_json.go]: File is not `goimports`-ed (from `goimports`)
