### PR TITLE
Fix zero's health endpoint to return json response

### LINKED ISSUE #5517: Zero's /health endpoint returns just "Ok" where the same Alpha's endpoint returns a JSON
I'm testing Dgraph 1.2.3 version and notice there is a difference in `/health` endpoints for Zero and Alpha. It would be good to unify that endpoint to return the same JSON structure.

Zero's response to `curl http://localhost:6080/health`
```
Ok
```

Alpha's reponse to `curl http://localhost:8080/health`:
```
{"version":"v1.2.3","instance":"alpha","uptime":59131}
```

### PR DESCRIPTION
**Pull request by jbhamra1**
Fixes #5517 Zero's /health endpoint just returns OK unlike Alpha's JSON output.

## Problem
curl http://alpha-hostname:alpha-http-port/health returns a JSON output whereas, curl http://zero-hostname:zero-http-port/health returns a plain text "OK".

## Solution
Added code to return a plain text output ("OK") for the "text/plain" to maintain the backward compatibility and return JSON output for "Accept: application/json" header.

Example Output:
$ curl http://localhost:58696/health
OK

$ curl -H "Accept: application/json" http://localhost:58696/health
{"instance":"zero","address":"zero1:5080","status":"healthy","version":"v23.0.0-16-g90139243f","uptime":9223372036,"lastEcho":1686137664}

### CODE REVIEW

File: dgraph/cmd/zero/http.go [hunk 1]
```diff
@@ -231,9 +234,46 @@ func (st *state) getState(w http.ResponseWriter, r *http.Request) {
...
+		Instance:    "zero",
+		Address:     x.WorkerConfig.MyAddr,
+		Status:      "healthy",
+		Version:     x.Version(),
+		Uptime:      int64(time.Since(x.WorkerConfig.StartTime) / time.Second),
+		LastEcho:    time.Now().Unix(),
+	}
+	jsonOut, err := json.Marshal(health)
+	if err != nil {
+		return nil, errors.Errorf("Unable to Marshal. Err %v", err)
```
Comment (mangalaman93) [inline dgraph/cmd/zero/http.go:251]: let's use small letters in the error message

File: dgraph/cmd/zero/http.go [hunk 2]
```diff
@@ -231,9 +234,46 @@ func (st *state) getState(w http.ResponseWriter, r *http.Request) {
...
+		case "application/json":
+			resp, err := (st.zero).zeroHealth(r.Context())
+			if err != nil {
+				x.SetStatus(w, x.Error, err.Error())
+				return
+			}
+			w.Header().Set("Content-Type", "application/json; charset=utf-8")
+			w.WriteHeader(http.StatusOK)
+			if _, err := w.Write(resp.Json); err != nil {
+				glog.Warningf("Could not send error msg=%+v code=%+v due to http error %+v", err.Error(), x.Error, err)
```
Comment (mangalaman93) [inline dgraph/cmd/zero/http.go:268]: same here, use small letters and maybe put either [] around the value of msg and code so that they are easy to separate. Do you need to do %+v for err.Error()?

**Review by mangalaman93 — CHANGES_REQUESTED** [review]
LGTM a few minor comments.

**Review by mangalaman93 — DISMISSED** [review]

**Review by harshil-goel — COMMENTED** [review]
Can you write some tests for it? Otherwise looks great.

File: dgraph/cmd/zero/http.go [hunk 3]
```diff
@@ -231,9 +234,46 @@ func (st *state) getState(w http.ResponseWriter, r *http.Request) {
...
+	case "application/json":
+		resp, err := (st.zero).zeroHealth(r.Context())
+		if err != nil {
+			x.SetStatus(w, x.Error, err.Error())
+			return
+		}
+		w.Header().Set("Content-Type", "application/json; charset=utf-8")
+		w.WriteHeader(http.StatusOK)
+		if _, err := w.Write(resp.Json); err != nil {
+			glog.Warningf("could not send error msg=[%v] code=[%+v] due to http error %+v", err.Error(), x.Error, err)
```
Comment (mangalaman93) [inline dgraph/cmd/zero/http.go:268]: same here.

File: dgraph/cmd/zero/zero_test.go [hunk 4]
```diff
@@ -112,3 +117,37 @@ func TestProposalKey(t *testing.T) {
...
+	require.NoError(t, err)
+
+	req.Header.Add("Accept", `application/json`)
+	resp, err := client.Do(req)
+	require.NoError(t, err)
+	defer resp.Body.Close()
+
+	body, err := ioutil.ReadAll(resp.Body)
+	require.NoError(t, err)
+	require.Equal(t, json.Valid(body), true)
```
Comment (mangalaman93) [inline dgraph/cmd/zero/zero_test.go:140]: nit: you could use require.True instead

**Review by mangalaman93 — CHANGES_REQUESTED** [review]
LGTM, a few minor comments. Please print the error message in a separate Go code and make sure they look okay in the logs and make sense.

File: dgraph/cmd/zero/http.go [hunk 5]
```diff
@@ -231,9 +234,46 @@ func (st *state) getState(w http.ResponseWriter, r *http.Request) {
 	}
 }
 
+func (s *Server) zeroHealth(ctx context.Context) (*api.Response, error) {
+	if ctx.Err() != nil {
+		return nil, ctx.Err()
```
Comment (harshil-goel) [inline dgraph/cmd/zero/http.go:239]: Can you wrap this error also? It would help to figure out where the error is actually coming from

File: dgraph/cmd/zero/http.go [hunk 6]
```diff
@@ -231,9 +234,46 @@ func (st *state) getState(w http.ResponseWriter, r *http.Request) {
...
+		Instance: "zero",
+		Address:  x.WorkerConfig.MyAddr,
+		Status:   "healthy",
+		Version:  x.Version(),
+		Uptime:   int64(time.Since(x.WorkerConfig.StartTime) / time.Second),
+		LastEcho: time.Now().Unix(),
+	}
+	jsonOut, err := json.Marshal(health)
+	if err != nil {
+		return nil, errors.Errorf("unable to marshal. error %+v", err)
```
Comment (harshil-goel) [inline dgraph/cmd/zero/http.go:251]: can you add more detail to the error, something like unable to marshal zero health. It makes finding the error in code much easier.

File: dgraph/cmd/zero/zero_test.go (hunk 4 above)
Comment (harshil-goel) [inline dgraph/cmd/zero/zero_test.go:140]: Can you also validate the content of the body?

File: dgraph/cmd/zero/http.go [hunk 7]
```diff
@@ -231,9 +234,46 @@ func (st *state) getState(w http.ResponseWriter, r *http.Request) {
 	}
 }
 
+func (s *Server) zeroHealth(ctx context.Context) (*api.Response, error) {
+	if ctx.Err() != nil {
+		return nil, ctx.Err()
+	}
+	health := pb.HealthInfo{
+		Instance: "zero",
```
[the remark this answers is not in the document]
Comment (mangalaman93) [reply dgraph/cmd/zero/http.go:242]: state endpoint has all the information, we don't need to make that redundant. Raft ID could be useful. If the alpha's health response has it, zero's response should also have it.

[the remark this answers is not in the document]
Comment (jbhamra1) [reply dgraph/cmd/zero/http.go:242]: Check the alpha health endpoint, we don't output raft id.

bash jassi Fri Jun 23 11:59:30 jassi/zero_health_issue_5517 dgraph > echo -e "\nALPHA"; curl http://localhost:63285/health; echo -e "\n"

ALPHA
[{"instance":"alpha","address":"alpha1:7080","status":"healthy","group":"1","version":"v23.0.0-38-g3e25acdc2","uptime":124,"lastEcho":1687501782,"ongoing":["opRollup"],"ee_features":["acl","multi_tenancy","encryption_at_rest","encrypted_backup_restore","encrypted_export","cdc"],"max_assigned":44}]

bash jassi Fri Jun 23 11:59:42 jassi/zero_health_issue_5517 dgraph >

**Review by mangalaman93 — APPROVED** [review]

File: dgraph/cmd/zero/zero_test.go [hunk 8]
```diff
@@ -112,3 +117,38 @@ func TestProposalKey(t *testing.T) {
...
+
+	req.Header.Add("Accept", `application/json`)
+	resp, err := client.Do(req)
+	require.NoError(t, err)
+	defer resp.Body.Close()
+
+	body, err := ioutil.ReadAll(resp.Body)
+	require.NoError(t, err)
+	require.NotEmpty(t, body)
+	require.True(t, json.Valid(body))
```
Comment (harshil-goel) [inline dgraph/cmd/zero/zero_test.go:141]: Can you validate the contest of the json body? What all headers are present and their values?

File: dgraph/cmd/zero/zero_test.go [hunk 9]
```diff
@@ -112,3 +118,58 @@ func TestProposalKey(t *testing.T) {
 	}
 	require.Equal(t, len(uniqueKeys), 10, "each iteration should create unique key")
 }
+
+func validateJsonHealthContent(body []byte) error {
```
Comment (mangalaman93) [inline dgraph/cmd/zero/zero_test.go:122]: You should use the stdlib encoding/json

File: dgraph/cmd/zero/zero_test.go [hunk 10]
```diff
@@ -112,3 +118,87 @@ func TestProposalKey(t *testing.T) {
...
+	var r map[string]interface{}
+	e := json.Unmarshal(body, &r)
```
Comment (mangalaman93) [inline dgraph/cmd/zero/zero_test.go:124]: let's just use `err`. I am so used to seeing that, that this looks odd to read.

File: dgraph/cmd/zero/zero_test.go [hunk 11]
```diff
@@ -112,3 +118,87 @@ func TestProposalKey(t *testing.T) {
...
+	if e != nil {
```
Comment (mangalaman93) [inline dgraph/cmd/zero/zero_test.go:125]: we should take `t` of type `*testing.T` as an arg to this function so that we can reduce the boiler plate code here. Once you have access to `t`, you could just do `require.NoError(t, err)`

File: dgraph/cmd/zero/zero_test.go [hunk 12]
```diff
@@ -112,3 +118,87 @@ func TestProposalKey(t *testing.T) {
...
+		return errors.Wrap(e, "json unmarshal error")
+	}
+
+	for k, v := range r {
+		switch k {
+		case "instance", "address", "status", "version":
+			s, e := v.(string)
+			if !e {
```
Comment (mangalaman93) [inline dgraph/cmd/zero/zero_test.go:133]: same here, use `t` and `require`

File: go.mod [hunk 13]
```diff
@@ -119,6 +120,9 @@ require (
 	github.com/spf13/afero v1.1.2 // indirect
 	github.com/spf13/jwalterweatherman v1.0.0 // indirect
 	github.com/subosito/gotenv v1.2.0 // indirect
+	github.com/tidwall/gjson v1.14.4 // indirect
```
Comment (mangalaman93) [inline go.mod:123]: we should clean this up, we are not adding any dependency as part of this change as far as I know.

File: dgraph/cmd/zero/zero_test.go [hunk 14]
```diff
@@ -112,3 +118,87 @@ func TestProposalKey(t *testing.T) {
...
+	var r map[string]interface{}
+	e := json.Unmarshal(body, &r)
+	if e != nil {
+		return errors.Wrap(e, "json unmarshal error")
+	}
+
+	for k, v := range r {
+		switch k {
+		case "instance", "address", "status", "version":
+			s, e := v.(string)
```
Comment (mangalaman93) [inline dgraph/cmd/zero/zero_test.go:132]: it would be okay to skip the error here because this is a test and if type is not string it'd panic which is kinda what we want.

File: dgraph/cmd/zero/zero_test.go [hunk 15]
```diff
@@ -112,3 +118,87 @@ func TestProposalKey(t *testing.T) {
...
 }
+
+func validateJsonHealthContent(body []byte) error {
+	var r map[string]interface{}
+	e := json.Unmarshal(body, &r)
+	if e != nil {
+		return errors.Wrap(e, "json unmarshal error")
+	}
+
+	for k, v := range r {
```
Comment (mangalaman93) [inline dgraph/cmd/zero/zero_test.go:129]: I personally would avoid using the switch case here because it doesn't make sure that all the fields are present. I would rather do it brute force and check for each field that I care about. It is okay if the code is a little repeated.

**Review by mangalaman93 — CHANGES_REQUESTED** [review]

**Review by mangalaman93 — APPROVED** [review]

**Review by harshil-goel — APPROVED** [review]
