### PR TITLE
graphql: ensure @id uniqueness within a mutation

### LINKED ISSUE #4882: @id directive not ensuring uniqueness when adding arrays
### What version of Dgraph are you using?
Dgraph v2.0.0-rc1 (`dgraph/standalone:v2.0.0-rc1` Docker image)
### Have you tried reproducing the issue with the latest release?
This is the latest release.

### What is the hardware spec (RAM, OS)?
MacBook Pro (15-inch, 2019), Mojave, 10.14.6

### Steps to reproduce the issue (command/config used to run Dgraph).
[Following the graphql example](https://graphql.dgraph.io/docs/walk-through-example/), and running the following query:

```gql
mutation {
  addAuthor(input: [
    { username: "John" },
    { username: "John" }
  ]) {
    author {
      username
    }
  }
}
```

I get a response like the following:

```json
{
  "data": {
    "addAuthor": {
      "author": [
        {
          "username": "John"
        },
        {
          "username": "John"
        }
      ]
    }
  }
}
```

When I query authors again, I can confirm that the multiple authors with the same `username` are indeed inserted into the database.

### Expected behaviour and actual result.
Looking at the schema definition:
```gql
type Author {
  username: String! @id
  # ...
}
```
The `username` field uses the `@id` directive, which in the example it says :

> The schema specified those usernames as `@id`, so Dgraph makes sure that they are unique and you’ll get an error if you try to add an author with a username that already exists (you can update an existing author with the updateAuthor mutation).

So I expect an error if I try to insert multiple authors with the same username.

### PR DESCRIPTION
**Pull request by abhimanyusinghgaur**
Fixes #4882.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/4959)

### CODE REVIEW

File: graphql/resolve/mutation_rewriter.go [hunk 1]
```diff
@@ -94,6 +119,14 @@ func NewDeleteRewriter() MutationRewriter {
 	return &deleteRewriter{}
 }
 
+// newXidMetadata returns a new empty *xidMetadata for storing the metadata.
+func newXidMetadata() *xidMetadata {
+	return &xidMetadata{
+		variableObjMap: make(map[string]interface{}, 0),
```
Comment (golangcibot) [inline graphql/resolve/mutation_rewriter.go]: S1019: should use make(map[string]interface{}) instead (from `gosimple`)

File: graphql/resolve/mutation_rewriter.go [hunk 2]
```diff
@@ -94,6 +119,14 @@ func NewDeleteRewriter() MutationRewriter {
...
+		queryExists:    make(map[string]bool, 0),
```
Comment (golangcibot) [inline graphql/resolve/mutation_rewriter.go]: S1019: should use make(map[string]bool) instead (from `gosimple`)

File: graphql/e2e/common/mutation.go [hunk 3]
```diff
@@ -2881,3 +2893,119 @@ func passwordTest(t *testing.T) {
...
+		currLevel["or"] = map[string]interface{}{
+			xidKey: map[string]interface{}{"eq": xidVals[i]},
+		}
+		currLevel = currLevel["or"].(map[string]interface{})
+	}
+
+	return filter
+}
+
+func getDuplicateXIDErrors(mutationName string, xidVals []string) x.GqlErrorList {
```
Comment (golangcibot) [inline graphql/e2e/common/mutation.go]: func `getDuplicateXIDErrors` is unused (from `unused`)
