### PR TITLE
An error was being returned when an empty response is expected.

### LINKED ISSUE #2610: Invalid error for semantically correct query
- What version of Dgraph are you using?
dgraph:latest

- Have you tried reproducing the issue with latest release?
Yes

- Steps to reproduce the issue (command/config used to run Dgraph).
`my_id` is indexed on `exact` in schema. Performing this mutation:
```
{
  set {
    _:test <pred_one> "one" .
    _:test <test> "" .
    _:test <my_id> "123" .
  }
}
```

- Expected behaviour and actual result.
Query should return no results:
```
{
  t as var(func: eq(my_id, "123")) @filter(has(test)) @cascade {
    p as pred_test
  }
  query(func: eq(my_id, "123")) @filter(uid(t) AND eq(val(p), "my test")) {
    expand(_all_)
  }
}
```
Instead, this error appears:
`: Expected a valid value map. But got empty.`

Modifying the query to be of this format returns the expected no results found:
```
{
  t as var(func: eq(my_id, "123")) @filter(has(test)) @cascade {
    p as pred_test
  }
  query(func: uid(t)) @filter(eq(my_id, "123") AND eq(val(p), "my test")) {
    expand(_all_)
  }
}
```

### PR DESCRIPTION
**Pull request by srfrog**
When testing inequality value vars with non-matching values, the
response was sent as an error although it should return empty result
if the query has correct syntax.

Closes #2610

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2611)

### CODE REVIEW

File: query/query.go [hunk 1]
```diff
@@ -1634,7 +1634,8 @@ func (sg *SubGraph) replaceVarInFunc() error {
 
 func (sg *SubGraph) ApplyIneqFunc() error {
 	if sg.Params.uidToVal == nil {
-		return x.Errorf("Expected a valid value map. But got empty.")
+		x.Println("Expected a valid value map. But got empty.")
```
Comment (manishrjain) [inline query/query.go]: You can get rid of the println here. Just return nil

**Comment by manishrjain** [comment]
LGTM. One comment.
