### PR TITLE
[BREAKING] Namespace dgraph internal types/predicates with `dgraph.`

### LINKED ISSUE #4878: Namespace dgraph internal types
### What version of Dgraph are you using?
latest:master

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
doesn't matter

### Steps to reproduce the issue (command/config used to run Dgraph).
* Run `dgraph zero`
* Run `dgraph alpha --acl_secret_file ee/acl/hmac-secret` (ACL enabled, this is just to get the ACL User `groot` inserted into Dgraph)
* Stop `alpha` instance
* Run `dgraph alpha` (Without ACL this time, so that we can make queries and mutations without token)
* Call `/admin/schema` with following POST body:
```
type  Device {
    uuid: String! @id @search(by: [hash])
    owner: User! @hasInverse(field: devices)
}

type User  {
    uuid: String! @id @search(by: [hash])
    devices: [Device] @hasInverse(field: owner)
}
```
2. Perform following GraphQL mutation (call `graphql` with given GraphQL body):
```
mutation {
  addDevice(input: [{
    uuid: "foo",
    owner: {
      uuid: "bar"
    }
  }]) {
    device {
      uuid
      owner {
        uuid
      }
    }
  }
}
```
3. Device gets added successfully, fine.
4. Now, perform following GraphQL query:
```
query {
  queryUser(filter: null) {
    uuid
    devices {
      uuid
    }
  }
}
```

### Expected behaviour and actual result.
* Expected Behaviour:
```
{
  "data": {
    "queryUser": [
      {
        "uuid": "bar",
        "devices": [
          {
            "uuid": "foo"
          }
        ]
      }
    ]
  }
}
```

* Actual Result:
```
{
  "errors": [
    {
      "message": "Non-nullable field 'uuid' (type String!) was not present in result from Dgraph.  GraphQL error propagation triggered.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "queryUser",
        1,
        "uuid"
      ]
    }
  ],
  "data": {
    "queryUser": [
      {
        "uuid": "bar",
        "devices": [
          {
            "uuid": "foo"
          }
        ]
      },
      null
    ]
  }
}
```

### Analysis
As a GraphQL user, I just declared some types, one of them (type User) happens to have same name as dgraph's internal type for ACL user. This causes a problem, as to how to identify which nodes are associated with user declared types and which ones with internal types. As a result, the actual results above contain errors, along with a null user in data.
If you call `/query` with following body, then you can see the reason why this happens:
```
query {
    q1(func: eq(dgraph.type, "User")) {
    	uid
    	dgraph.xid
    	expand(_all_) {
	    	expand(_all_)
    	}
    }
  }
```
following results are returned:
```
{
    "data": {
        "q1": [
            {
                "uid": "0x3",
                "User.uuid": "bar",
                "User.devices": [
                    {
                        "Device.uuid": "foo"
                    }
                ]
            },
            {
                "uid": "0x5",
                "dgraph.xid": "groot"
            }
        ]
    },
    "extensions": {
        "server_latency": {
            "parsing_ns": 79899,
            "processing_ns": 2018313,
            "encoding_ns": 28383,
            "assign_timestamp_ns": 547917,
            "total_ns": 2755443
        },
        "txn": {
            "start_ts": 25
        },
        "metrics": {
            "num_uids": {
                "Device.owner": 1,
                "Device.uuid": 1,
                "User.devices": 2,
                "User.uuid": 2,
                "dgraph.type": 0,
                "dgraph.xid": 2,
                "uid": 2
            }
        }
    }
}
```
As `groot` is also a `User`, so it is also returned by dgraph in response to query, although, `groot` was never inserted by us, as it got inserted by ACL instance.

So, any types which are used by dgraph internally should be namespaced, in order to avoid collision with user declared types. For example, ACL `User` can be `__User` or `dgraph.User`, or something like that.

### PR DESCRIPTION
**Pull request by animesh2049**
Dgraph's internal types `User`, `Group` and `Rule` were too generic. Prefixed them with `dgraph.type` so that there is no chance of collision with user-defined types.

Also, reserved `dgraph.` as the namespace for dgraph's internal types/predicates so that no user could create any such type/predicate.

Fixes #4878.
Fixes #DGRAPH-1090.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/5185)

 
 
 
 
 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-d14923aaea-68875.surge.sh)

### CODE REVIEW

File: x/x.go [hunk 1]
```diff
@@ -121,12 +121,10 @@ const (
...
 
 	InitialTypes = `
-"types": [
-{"fields":[{"name":"dgraph.graphql.schema"},{"name":"dgraph.graphql.xid"}],"name":"dgraph.graphql"},
-{"fields": [{"name": "dgraph.password"},{"name": "dgraph.xid"},{"name": "dgraph.user.group"}],"name": "User"},
-{"fields": [{"name": "dgraph.acl.rule"},{"name": "dgraph.xid"}],"name": "Group"},
-{"fields": [{"name": "dgraph.rule.predicate"},{"name": "dgraph.rule.permission"}],"name": "Rule"}
-]`
+	"types": [{"fields": [{"name": "dgraph.graphql.schema"}],"name": "dgraph.graphql"},
+{"fields": [{"name": "dgraph.password"},{"name": "dgraph.xid"},{"name": "dgraph.user.group"}],"name": "dgraph.type.User"},
```
Comment (golangcibot) [inline x/x.go:125]: line is 122 characters (from `lll`)

File: x/x.go [hunk 2]
```diff
@@ -121,12 +121,10 @@ const (
...
+{"fields": [{"name": "dgraph.acl.rule"},{"name": "dgraph.xid"}],"name": "dgraph.type.Group"},
+{"fields": [{"name": "dgraph.rule.predicate"},{"name": "dgraph.rule.permission"}],"name": "dgraph.type.Rule"}]`
```
Comment (golangcibot) [inline x/x.go:127]: line is 111 characters (from `lll`)

File: edgraph/access_ee.go [hunk 3]
```diff
@@ -825,8 +825,8 @@ func authorizeGuardians(ctx context.Context) error {
 	addUserFilterToQuery applies makes sure that a user can access only its own
 	acl info by applying filter of userid and groupid to acl predicates. A query like
 	Conversion pattern:
-	* me(func: type(Group)) -> me(func: type(Group)) @filter(eq("dgraph.xid", groupIds...))
-	* me(func: type(User)) -> me(func: type(User)) @filter(eq("dgraph.xid", userId))
+	* me(func: type(dgraph.type.Group)) -> me(func: type(dgraph.type.Group)) @filter(eq("dgraph.xid", groupIds...))
```
Comment (golangcibot) [inline edgraph/access_ee.go:828]: line is 112 characters (from `lll`)

File: edgraph/access_ee.go [hunk 4]
```diff
@@ -825,8 +825,8 @@ func authorizeGuardians(ctx context.Context) error {
...
+	* me(func: type(dgraph.type.User)) -> me(func: type(dgraph.type.User)) @filter(eq("dgraph.xid", userId))
```
Comment (golangcibot) [inline edgraph/access_ee.go:829]: line is 105 characters (from `lll`)

File: edgraph/access_ee.go [hunk 5]
```diff
@@ -915,7 +915,7 @@ func groupFilter(groupIds []string) *gql.FilterTree {
 
 /*
  addUserFilterToFilter makes sure that user can't misue filters to access other user's info.
- If the *filter* have type(Group) or type(User) functions, it generate a *newFilter* with function
+ If the *filter* have type(dgraph.type.Group) or type(dgraph.type.User) functions, it generate a *newFilter* with function
```
Comment (golangcibot) [inline edgraph/access_ee.go:918]: line is 122 characters (from `lll`)

File: x/x.go [hunk 6]
```diff
@@ -121,12 +121,10 @@ const (
 `
 
 	InitialTypes = `
-"types": [
-{"fields":[{"name":"dgraph.graphql.schema"},{"name":"dgraph.graphql.xid"}],"name":"dgraph.graphql"},
-{"fields": [{"name": "dgraph.password"},{"name": "dgraph.xid"},{"name": "dgraph.user.group"}],"name": "User"},
-{"fields": [{"name": "dgraph.acl.rule"},{"name": "dgraph.xid"}],"name": "Group"},
-{"fields": [{"name": "dgraph.rule.predicate"},{"name": "dgraph.rule.permission"}],"name": "Rule"}
-]`
+	"types": [{"fields": [{"name": "dgraph.graphql.schema"},{"name": "dgraph.graphql.xid"}],"name": "dgraph.graphql"},
```
Comment (golangcibot) [inline x/x.go:124]: line is 115 characters (from `lll`)
