### PR TITLE
Overwrite values for uid predicates

### LINKED ISSUE #4879: List value returned for a non-list uid predicate
### What version of Dgraph are you using?
latest:master

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
doesn't matter

### Steps to reproduce the issue (command/config used to run Dgraph).
* Run `dgraph zero`
* Run `dgraph alpha`
* Set following dgraph schema:
```
uuid: string @index(hash) .
author: uid .
post: [uid] .

type Post {
   uuid
   author
}

type Author {
	uuid
	post
}
```
* That means, a Post can have only one Author, while an Author can have multiple Posts.
* Perform following mutation:
```
{
	"set": {
			"uid": "_:Post1",
			"uuid": "Post1",
			"dgraph.type": "Post",
			"author": {
				"uid": "_:Author1",
				"uuid": "Author1",
				"dgraph.type": "Author"
			}
		}
}
```
* Now, perform following query, to see what mutation did:
```
query {
    q1(func: eq(dgraph.type, "Post")) {
    	uid
    	uuid
    	author {
    		uid
    		uuid
    	}
    }
  }
```
* Result will be something like this (and that is fine):
```
{
    "data": {
        "q1": [
            {
                "uid": "0x2",
                "uuid": "Post1",
                "author": {
                    "uid": "0x1",
                    "uuid": "Author1"
                }
            }
        ]
    },
    "extensions": {
        "server_latency": {
            "parsing_ns": 68739,
            "processing_ns": 2970060,
            "encoding_ns": 19707,
            "assign_timestamp_ns": 600806,
            "total_ns": 3744032
        },
        "txn": {
            "start_ts": 12
        },
        "metrics": {
            "num_uids": {
                "author": 1,
                "dgraph.type": 0,
                "post": 1,
                "uid": 2,
                "uuid": 2
            }
        }
    }
}
```
* Let's do one more mutation, to set the author for Post1 to a new author:
```
{
	"set": {
			"uid": "0x2",
			"author": {
				"uid": "_:Author2",
				"uuid": "Author2",
				"dgraph.type": "Author"
			}
		}
}
```
* Again, perform the query to see results:
```
query {
    q1(func: eq(dgraph.type, "Post")) {
    	uid
    	uuid
    	author {
    		uid
    		uuid
    	}
    }
  }
```

### Expected behaviour and actual result.
* Expected behaviour:
```
{
    "data": {
        "q1": [
            {
                "uid": "0x2",
                "uuid": "Post1",
                "author": {
                    "uid": "0x3",
                    "uuid": "Author2"
                }
            }
        ]
    },
    ...
}
```
* Actual Results:
```
{
    "data": {
        "q1": [
            {
                "uid": "0x2",
                "uuid": "Post1",
                "author": {
                    "uid": "0x1",
                    "uuid": "Author1",
                    "uid": "0x3",
                    "uuid": "Author2"
                }
            }
        ]
    },
    ...
}
```

`Post1` should have `Author2` as its only author, but it gives both `Author1` and `Author2` .

### PR DESCRIPTION
**Pull request by martinmr**
When the warning to delete and re-add the value was removed, non-list uid
predicates were not being overwritten. This fixes this by iterating over the list
and replacing theexisting postings with a copy with the operation set to a delete.

It also adds a test to prevent this from happening again.

Fixes #4879

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/4883)

 
 

Docs Preview: [Dgraph Preview](https://dgraph-1d51086179-47992.surge.sh)

### CODE REVIEW

File: posting/list.go [hunk 1]
```diff
@@ -323,16 +324,36 @@ func (l *List) updateMutationLayer(mpost *pb.Posting) {
...
 		}
 		l.mutationMap[mpost.StartTs] = plist
+	}
+
+	if !isListAttr && mpost.PostingType == pb.Posting_REF {
+		// This handles predicates of type uid. The fingerprint approach that is used
+		// in other scalar types does not work because it would replace the uid of
+		// the posting. Intead, the list is traversed and new postings are added for
+		// each existing value with the Op value set to delete.
+		l.iterate(mpost.StartTs, 0, func(obj *pb.Posting) error {
```
Comment (golangcibot) [inline posting/list.go]: Error return value of `l.iterate` is not checked (from `errcheck`)

File: posting/list.go [hunk 2]
```diff
@@ -399,17 +429,26 @@ func (l *List) addMutationInternal(ctx context.Context, txn *Txn, t *pb.Directed
...
-	var conflictKey uint64
+	// Check whether this mutation is an update for a predicate of type uid.
 	pk, err := x.Parse(l.key)
 	if err != nil {
 		return errors.Wrapf(err, "cannot parse key when adding mutation to list with key %v",
 			l.key)
 	}
+	pred, ok := schema.State().Get(t.Attr)
+	isSingleUidUpdate := ok && !pred.GetList() && pred.GetValueType() == pb.Posting_UID &&
+		pk.IsData() && mpost.Op == Set && mpost.PostingType == pb.Posting_REF
```
Comment (golangcibot) [inline posting/list.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)
```suggestion
		pk.IsData() && mpost.Op == Set && mpost.PostingType == pb.Posting_REF
```

Comment (golangcibot) [inline posting/list.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)
```suggestion
		pk.IsData() && mpost.Op == Set && mpost.PostingType == pb.Posting_REF
```
