### PR TITLE
graphql: Add fragment support

### LINKED ISSUE #4830: GraphQL Fragment spread not working in Dgraph 2.0
### What version of Dgraph are you using?
Probably the latest as exposed by
https://dgraph.io/graphql

### Have you tried reproducing the issue with the latest release?
NA

### What is the hardware spec (RAM, OS)?
Not sure

### Steps to reproduce the issue (command/config used to run Dgraph).
1. Goto https://dgraph.io/graphql
2. Execute query to check if results are returned
image

3. Modify the query to use this GraphQL query in GraphiQL
```
query {
	queryLocation(
		filter: { name: {eq: "Bangalore"} }
	) {
		...locationFragment
	}
}

fragment locationFragment on Location {
  name
  	featured_in_films (
			order: { desc: initial_release_date },
			first: 3
		) {
			name
			initial_release_date
			featured_locations {
				name
			}
		}
}
```
4. No results returned
image

### Expected behaviour and actual result.

Expected Behaviour should be same as the results of the query without the named fragment

### PR DESCRIPTION
**Pull request by abhimanyusinghgaur**
This PR adds fragment support for GraphQL on following types of fields:
* Interface
* Union
* Object

If any of above kind of fields contains a fragment(inline or fragment spread) at any level in its selection set, then its selection set is modified to directly include the fields inside the fragment's selection set.

Introspection system still has its own mechanism to handle fragments.

Fixes #4830 

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/4902)

### CODE REVIEW

File: graphql/e2e/common/error.go [hunk 1]
```diff
@@ -275,6 +275,10 @@ func (dg *panicClient) Mutate(
 	panic(panicMsg)
 }
 
+type contextClient struct {
```
Comment (golangcibot) [inline graphql/e2e/common/error.go]: type `contextClient` is unused (from `unused`)
